/// Flutter icons Heading
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Heading
///      fonts:
///       - asset: fonts/Heading.ttf
///
///
///

import 'package:flutter/widgets.dart';

class Heading {
  Heading._();

  static const _kFontFam = 'Heading';
  static const String? _kFontPkg = null;

  static const IconData type_h1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_h4 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_h2 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_h5 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_h3 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_h6 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
